# This workflow will install Python dependencies, run tests and lint with a variety of Python versions
# For more information see: https://docs.github.com/en/actions/automating-builds-and-tests/building-and-testing-python

name: Build febid for win, mac, linux and test publishing on Test.Pypi

on:
  workflow_dispatch:

jobs:
    build_wheels:
      name: Build wheels on ${{ matrix.os }}
      runs-on: ${{ matrix.os }}
      strategy:
        fail-fast: false
        matrix:
          os: [ubuntu-latest, windows-latest, macos-13, macos-14]
          include:
            - arch: arm64
              os: macos-latest
              pypthon-version: "3.9-3.11"

      steps:
      - uses: actions/checkout@v4

      - name: Build wheels
        uses: pypa/cibuildwheel@v2.19.2
        env:
          CIBW_BUILD: cp39-* cp310-* cp311-*
          CIBW_SKIP: "*_i686"

      - uses: actions/upload-artifact@v4
        with:
                name: cibw-wheels-${{ matrix.os }}-${{ strategy.job-index }}
                path: ./wheelhouse/*.whl

    build_sdist:
     name: Build source distribution
     runs-on: ubuntu-latest
     steps:
     - uses: actions/checkout@v4

     - name: Build sdist
       run: pipx run build --sdist

     - uses: actions/upload-artifact@v4
       with:
          name: cibw-sdist_test
          path: dist/*.tar.gz

    upload_pypi:
     needs: [build_wheels, build_sdist]
     runs-on: ubuntu-latest
     environment:
          name: testpypi
          url: https://test.pypi.org/project/febid/
     permissions:
      id-token: write
     steps:
     - uses: actions/download-artifact@v4
       with:
          # unpacks all CIBW artifacts into dist/
          pattern: cibw-*
          path: dist
          merge-multiple: true

     - name: Publish package distributions to TestPyPI
       uses: pypa/gh-action-pypi-publish@release/v1
       with:
          repository-url: https://test.pypi.org/legacy/
          password: ${{ secrets.TEST_PYPI_PASSWORD }}
